experiments:

# EXPERIMENT 1: EFFECTS OF COMPETITION ON THE ILLUSION OF CONTROL
- id: competition
  title: 'Конкуренция'

  conditions:
  - id: dapper
    title: 'Dapper'
  - id: schnook
    title: 'Schnook'

  variations:
  - id: lower_emphasis
    title: 'Мягкое подчеркивание уверенности соперника'
  - id: higher_emphasis
    title: 'Сильное подчеркивание уверенности соперника'
  - id: bets_in_dollars
    title: 'Ставки в долларах, а не в центах'
  
  measures:
  - id: bet_1
    title: 'Ставка субъекта в 1-ом раунде'
    parser:
      name: IntegerParser
      params:
        range_min: 0
        range_max: 25
  - id: bet_2
    title: 'Ставка субъекта во 2-ом раунде'
    parser:
      name: IntegerParser
      params:
        range_min: 0
        range_max: 25
  - id: bet_3
    title: 'Ставка субъекта в 3-ем раунде'
    parser:
      name: IntegerParser
      params:
        range_min: 0
        range_max: 25
  - id: bet_4
    title: 'Ставка субъекта в 4-ом раунде'
    parser:
      name: IntegerParser
      params:
        range_min: 0
        range_max: 25
  - id: confidence
    title: 'Воспринимаемая субъектом уверенность соперника'
    parser:
      name: IntegerParser
      params:
        range_min: 1
        range_max: 6
