model_templates:
- id: default
  default:
    settings:
      max_retries: 11234
      retry_delay: 0.5
      system_message: 'Respond only as the character, continuing their line or filling gaps (___). No extra words.'


models:

- id: gpt4omini
  name: 'GPT-4o Mini'
  provider: 'OpenAI'
  provider_model_name: 'gpt-4o-mini'
  model_template_id: default
