participant_templates:

- id: competition
  default:
    gender: male
    name: X



participants:

# EXPERIMENT 1: EFFECTS OF COMPETITION ON THE ILLUSION OF CONTROL
- participant_template_id: competition
  experiments_conditions: competition,dapper
- participant_template_id: competition
  experiments_conditions: competition,dapper
- participant_template_id: competition
  experiments_conditions: competition,dapper
- participant_template_id: competition
  experiments_conditions: competition,dapper
- participant_template_id: competition
  experiments_conditions: competition,dapper
- participant_template_id: competition
  experiments_conditions: competition,dapper
- participant_template_id: competition
  experiments_conditions: competition,dapper
- participant_template_id: competition
  experiments_conditions: competition,dapper
- participant_template_id: competition
  experiments_conditions: competition,dapper
- participant_template_id: competition
  experiments_conditions: competition,dapper
- participant_template_id: competition
  experiments_conditions: competition,dapper
- participant_template_id: competition
  experiments_conditions: competition,dapper
- participant_template_id: competition
  experiments_conditions: competition,dapper
- participant_template_id: competition
  experiments_conditions: competition,dapper
- participant_template_id: competition
  experiments_conditions: competition,dapper
- participant_template_id: competition
  experiments_conditions: competition,dapper
- participant_template_id: competition
  experiments_conditions: competition,dapper
- participant_template_id: competition
  experiments_conditions: competition,dapper
- participant_template_id: competition
  experiments_conditions: competition,schnook
- participant_template_id: competition
  experiments_conditions: competition,schnook
- participant_template_id: competition
  experiments_conditions: competition,schnook
- participant_template_id: competition
  experiments_conditions: competition,schnook
- participant_template_id: competition
  experiments_conditions: competition,schnook
- participant_template_id: competition
  experiments_conditions: competition,schnook
- participant_template_id: competition
  experiments_conditions: competition,schnook
- participant_template_id: competition
  experiments_conditions: competition,schnook
- participant_template_id: competition
  experiments_conditions: competition,schnook
- participant_template_id: competition
  experiments_conditions: competition,schnook
- participant_template_id: competition
  experiments_conditions: competition,schnook
- participant_template_id: competition
  experiments_conditions: competition,schnook
- participant_template_id: competition
  experiments_conditions: competition,schnook
- participant_template_id: competition
  experiments_conditions: competition,schnook
- participant_template_id: competition
  experiments_conditions: competition,schnook
- participant_template_id: competition
  experiments_conditions: competition,schnook
- participant_template_id: competition
  experiments_conditions: competition,schnook
- participant_template_id: competition
  experiments_conditions: competition,schnook
