participant_templates:

- id: competition
  default:
    gender: male
    name: X
- id: choice_male
  default:
    gender: male
    name: X
- id: choice_female
  default:
    gender: female
    name: X



participants:

# EXPERIMENT 1: EFFECTS OF COMPETITION ON THE ILLUSION OF CONTROL
- participant_template_id: competition
  experiments_conditions: competition,dapper
- participant_template_id: competition
  experiments_conditions: competition,dapper
- participant_template_id: competition
  experiments_conditions: competition,dapper
- participant_template_id: competition
  experiments_conditions: competition,dapper
- participant_template_id: competition
  experiments_conditions: competition,dapper
- participant_template_id: competition
  experiments_conditions: competition,dapper
- participant_template_id: competition
  experiments_conditions: competition,dapper
- participant_template_id: competition
  experiments_conditions: competition,dapper
- participant_template_id: competition
  experiments_conditions: competition,dapper
- participant_template_id: competition
  experiments_conditions: competition,dapper
- participant_template_id: competition
  experiments_conditions: competition,dapper
- participant_template_id: competition
  experiments_conditions: competition,dapper
- participant_template_id: competition
  experiments_conditions: competition,dapper
- participant_template_id: competition
  experiments_conditions: competition,dapper
- participant_template_id: competition
  experiments_conditions: competition,dapper
- participant_template_id: competition
  experiments_conditions: competition,dapper
- participant_template_id: competition
  experiments_conditions: competition,dapper
- participant_template_id: competition
  experiments_conditions: competition,dapper
- participant_template_id: competition
  experiments_conditions: competition,schnook
- participant_template_id: competition
  experiments_conditions: competition,schnook
- participant_template_id: competition
  experiments_conditions: competition,schnook
- participant_template_id: competition
  experiments_conditions: competition,schnook
- participant_template_id: competition
  experiments_conditions: competition,schnook
- participant_template_id: competition
  experiments_conditions: competition,schnook
- participant_template_id: competition
  experiments_conditions: competition,schnook
- participant_template_id: competition
  experiments_conditions: competition,schnook
- participant_template_id: competition
  experiments_conditions: competition,schnook
- participant_template_id: competition
  experiments_conditions: competition,schnook
- participant_template_id: competition
  experiments_conditions: competition,schnook
- participant_template_id: competition
  experiments_conditions: competition,schnook
- participant_template_id: competition
  experiments_conditions: competition,schnook
- participant_template_id: competition
  experiments_conditions: competition,schnook
- participant_template_id: competition
  experiments_conditions: competition,schnook
- participant_template_id: competition
  experiments_conditions: competition,schnook
- participant_template_id: competition
  experiments_conditions: competition,schnook
- participant_template_id: competition
  experiments_conditions: competition,schnook

# EXPERIMENT 2: EFFECTS OF CHOICE ON THE ILLUSION OF CONTROL
- participant_template_id: choice_male
  experiments_conditions: choice,choice
- participant_template_id: choice_male
  experiments_conditions: choice,choice
- participant_template_id: choice_male
  experiments_conditions: choice,choice
- participant_template_id: choice_male
  experiments_conditions: choice,choice
- participant_template_id: choice_male
  experiments_conditions: choice,choice
- participant_template_id: choice_male
  experiments_conditions: choice,choice
- participant_template_id: choice_male
  experiments_conditions: choice,choice
- participant_template_id: choice_male
  experiments_conditions: choice,choice
- participant_template_id: choice_male
  experiments_conditions: choice,choice
- participant_template_id: choice_male
  experiments_conditions: choice,choice
- participant_template_id: choice_male
  experiments_conditions: choice,choice
- participant_template_id: choice_male
  experiments_conditions: choice,choice
- participant_template_id: choice_male
  experiments_conditions: choice,choice
- participant_template_id: choice_male
  experiments_conditions: choice,choice
- participant_template_id: choice_male
  experiments_conditions: choice,choice
- participant_template_id: choice_male
  experiments_conditions: choice,choice
- participant_template_id: choice_male
  experiments_conditions: choice,choice
- participant_template_id: choice_male
  experiments_conditions: choice,choice
- participant_template_id: choice_male
  experiments_conditions: choice,choice
- participant_template_id: choice_male
  experiments_conditions: choice,choice
- participant_template_id: choice_male
  experiments_conditions: choice,choice
- participant_template_id: choice_male
  experiments_conditions: choice,choice
- participant_template_id: choice_male
  experiments_conditions: choice,choice
- participant_template_id: choice_male
  experiments_conditions: choice,choice
- participant_template_id: choice_female
  experiments_conditions: choice,choice
- participant_template_id: choice_female
  experiments_conditions: choice,choice
- participant_template_id: choice_female
  experiments_conditions: choice,choice
- participant_template_id: choice_female
  experiments_conditions: choice,choice
- participant_template_id: choice_female
  experiments_conditions: choice,choice
- participant_template_id: choice_female
  experiments_conditions: choice,choice
- participant_template_id: choice_female
  experiments_conditions: choice,choice
- participant_template_id: choice_female
  experiments_conditions: choice,choice
- participant_template_id: choice_female
  experiments_conditions: choice,choice
- participant_template_id: choice_female
  experiments_conditions: choice,choice
- participant_template_id: choice_female
  experiments_conditions: choice,choice
- participant_template_id: choice_female
  experiments_conditions: choice,choice
- participant_template_id: choice_female
  experiments_conditions: choice,choice
- participant_template_id: choice_female
  experiments_conditions: choice,choice
- participant_template_id: choice_female
  experiments_conditions: choice,choice
- participant_template_id: choice_female
  experiments_conditions: choice,choice
- participant_template_id: choice_female
  experiments_conditions: choice,choice
- participant_template_id: choice_female
  experiments_conditions: choice,choice
- participant_template_id: choice_female
  experiments_conditions: choice,choice
- participant_template_id: choice_female
  experiments_conditions: choice,choice
- participant_template_id: choice_female
  experiments_conditions: choice,choice
- participant_template_id: choice_female
  experiments_conditions: choice,choice
- participant_template_id: choice_female
  experiments_conditions: choice,choice
- participant_template_id: choice_female
  experiments_conditions: choice,choice
- participant_template_id: choice_male
  experiments_conditions: choice,no_choice
- participant_template_id: choice_male
  experiments_conditions: choice,no_choice
- participant_template_id: choice_male
  experiments_conditions: choice,no_choice
- participant_template_id: choice_male
  experiments_conditions: choice,no_choice
- participant_template_id: choice_male
  experiments_conditions: choice,no_choice
- participant_template_id: choice_male
  experiments_conditions: choice,no_choice
- participant_template_id: choice_male
  experiments_conditions: choice,no_choice
- participant_template_id: choice_male
  experiments_conditions: choice,no_choice
- participant_template_id: choice_male
  experiments_conditions: choice,no_choice
- participant_template_id: choice_male
  experiments_conditions: choice,no_choice
- participant_template_id: choice_male
  experiments_conditions: choice,no_choice
- participant_template_id: choice_male
  experiments_conditions: choice,no_choice
- participant_template_id: choice_male
  experiments_conditions: choice,no_choice
- participant_template_id: choice_male
  experiments_conditions: choice,no_choice
- participant_template_id: choice_male
  experiments_conditions: choice,no_choice
- participant_template_id: choice_male
  experiments_conditions: choice,no_choice
- participant_template_id: choice_male
  experiments_conditions: choice,no_choice
- participant_template_id: choice_male
  experiments_conditions: choice,no_choice
- participant_template_id: choice_male
  experiments_conditions: choice,no_choice
- participant_template_id: choice_male
  experiments_conditions: choice,no_choice
- participant_template_id: choice_male
  experiments_conditions: choice,no_choice
- participant_template_id: choice_male
  experiments_conditions: choice,no_choice
- participant_template_id: choice_male
  experiments_conditions: choice,no_choice
- participant_template_id: choice_male
  experiments_conditions: choice,no_choice
- participant_template_id: choice_female
  experiments_conditions: choice,no_choice
- participant_template_id: choice_female
  experiments_conditions: choice,no_choice
- participant_template_id: choice_female
  experiments_conditions: choice,no_choice
- participant_template_id: choice_female
  experiments_conditions: choice,no_choice
- participant_template_id: choice_female
  experiments_conditions: choice,no_choice
- participant_template_id: choice_female
  experiments_conditions: choice,no_choice
- participant_template_id: choice_female
  experiments_conditions: choice,no_choice
- participant_template_id: choice_female
  experiments_conditions: choice,no_choice
- participant_template_id: choice_female
  experiments_conditions: choice,no_choice
- participant_template_id: choice_female
  experiments_conditions: choice,no_choice
- participant_template_id: choice_female
  experiments_conditions: choice,no_choice
- participant_template_id: choice_female
  experiments_conditions: choice,no_choice
- participant_template_id: choice_female
  experiments_conditions: choice,no_choice
- participant_template_id: choice_female
  experiments_conditions: choice,no_choice
- participant_template_id: choice_female
  experiments_conditions: choice,no_choice
- participant_template_id: choice_female
  experiments_conditions: choice,no_choice
- participant_template_id: choice_female
  experiments_conditions: choice,no_choice
- participant_template_id: choice_female
  experiments_conditions: choice,no_choice
- participant_template_id: choice_female
  experiments_conditions: choice,no_choice
- participant_template_id: choice_female
  experiments_conditions: choice,no_choice
- participant_template_id: choice_female
  experiments_conditions: choice,no_choice
- participant_template_id: choice_female
  experiments_conditions: choice,no_choice
- participant_template_id: choice_female
  experiments_conditions: choice,no_choice
- participant_template_id: choice_female
  experiments_conditions: choice,no_choice
