runs:

- id: test
  title: 'Test Run'

  experiments:
  - experiment_id: competition
    models:
    - model_id: gpt4omini
      n_iterations: 1

- id: competition
  title: 'Run "EXPERIMENT 1: EFFECTS OF COMPETITION ON THE ILLUSION OF CONTROL"'

  experiments:
  - experiment_id: competition
    models:
    - model_id: gpt4omini
      n_iterations: 1
  - experiment_id: competition
    variation_id: s
    models:
    - model_id: gpt4omini
      n_iterations: 1
