scenarios:

# EXPERIMENT 1: EFFECTS OF COMPETITION ON THE ILLUSION OF CONTROL
- experiment_id: competition

  steps:

  - text: ''
    variations:
    - variation_id: fully_rational
      text: |
        {{participant}} is a fully rational economic agent.

  - text: |
      {{participant}} is an undergraduate enrolled in the introductory psychology course at Yale University. {{participant}} was recruited by an advertisement that offered course credit and a chance to win money for participation in a study on the relationship between cognitive and physiological responses.
      When {{participant}} entered the room in which the experiment was to take place, he found waiting an another subject (hereafter Subject).
    
  - condition_id: dapper
    text: |
      Subject appeared supremely confident and outgoing, dressed in an impeccably tailored sports coat. With an air of natural authority, he introduced himself and casually directed {{participant}}'s attention to the room's posted sign. The sign indicated the experimenter would return shortly and requested to complete a brief questionnaire about diet and family history while waiting. For ten minutes, they conversed effortlessly, primarily about sports, with the Subject leading the discussion in a relaxed, self-assured manner. Following this smooth interaction, he then knocked on the adjoining wall — a decisive, nonchalant tap to summon the experimenter.
    variations:
    - variation_id: lower_emphasis
      text: |
        Text
    - variation_id: higher_emphasis
      text: |
        Text
    - variation_id: without_emphasis
      text: ''

  - condition_id: schnook
    text: |
      Subject appeared distinctly shy and insecure, sporting a nervous twitch and an ill-fitting sports coat that seemed too small for him. He introduced himself with noticeable hesitation and timidly pointed out the sign posted in the room. The sign stated the experimenter would be right back and asked to fill out a brief questionnaire about diet and family diseases while waiting. Their conversation over the next ten minutes was painfully awkward, stiltedly circling topics like sports events. After this uncomfortable exchange, Subject then raised a hesitant, uncertain hand and knocked on the separating wall — a weak, almost apologetic sound.
    variations:
    - variation_id: lower_emphasis
      text: |
        Text
    - variation_id: higher_emphasis
      text: |
        Text
    - variation_id: without_emphasis
      text: ''

  - text: |
      Subject removed his coat before the experimenter entered the room. After she apologized for being late, the experimenter instructed them to sit down and not talk while she prepared the materials for the study. Subject and {{participant}} sat at a table facing each other.
      After the experimenter placed a televolter, alcohol, gauze sponges, electrodes, electrode gel, and tape on the table, she recited the instructions.
      Experimenter: We're interested in the effects of certain motoric and cognitive responses on physiological responses. Specifically, we're interested in changes in skin resistance as a function of pressured and nonpressured tasks. The study was designed so that, hopefully, you will enjoy the tasks while I get the information I need. You'll have the chance to either win or lose money so it should be fun but there's no guarantee that you'll walk out of here with any extra money. Okay, now the first thing I want you to do is tape these electrodes to your hands. I want to put it on the hand that you don't write with. Don't worry, none of this will hurt.
  
  - text: |
      The experimenter tapes electrodes, plugs in the televolter, andbrings out a deck of playing cards.
      Experimenter: The first task is a card game. The rules are that you'll each choose a card from the deck, and whoever selects the higher card wins that round. There will be four rounds, and before each you'll write down how much you want to bet. You can wager anywhere from 0 to 25 cents on each round. You'll then show your bets to me but not to each other. Don't look at the card you choose. This way your bets and the outcomes won't influence your physiological responses on the next task. I'll turn the cards over for you and figure out how much was won or lost later with each of you individually. The betting is just between each of you and myself, so if you win I'll pay you and if you lose you'll pay me either in money or subject time. Are you willing to participate?
    variations:
    - variation_id: bets_in_dollars
      text: |
        The experimenter tapes electrodes, plugs in the televolter, andbrings out a deck of playing cards.
        Experimenter: The first task is a card game. The rules are that you'll each choose a card from the deck, and whoever selects the higher card wins that round. There will be four rounds, and before each you'll write down how much you want to bet. You can wager anywhere from 0 to 25 $ on each round. You'll then show your bets to me but not to each other. Don't look at the card you choose. This way your bets and the outcomes won't influence your physiological responses on the next task. I'll turn the cards over for you and figure out how much was won or lost later with each of you individually. The betting is just between each of you and myself, so if you win I'll pay you and if you lose you'll pay me either in money or subject time. Are you willing to participate?

  - condition_id: dapper
    text: |
      Sure!
    variations:
    - variation_id: lower_emphasis
      text: |
        Sure.
    - variation_id: higher_emphasis
      text: |
        Yeah! Sure!
    - variation_id: without_emphasis
      text: |
        Sure.

  - condition_id: schnook
    text: |
      S... sure.
    variations:
    - variation_id: lower_emphasis
      text: |
        Sure.
    - variation_id: higher_emphasis
      text: |
        S... s... sure.
    - variation_id: without_emphasis
      text: |
        Sure.
  
  - text: |
      {{participant}}: Sure.
      Experimenter: Good, now we can begin. Don't write down your bet until I say ready so that I can get a baseline reading.
      Experimenter: Okay, now write your bets.
    
  - measure_id: bet_1
    text: |
      Experimenter started recording signals about skin resistance fluctuations. Subject wrote his bet on the paper. {{participant}} writes ___ cents (from 0 to 25 cents).
    variations:
    - variation_id: bets_in_dollars
      text: |
        Experimenter started recording signals about skin resistance fluctuations. Subject wrote his bet on the paper. {{participant}} writes ___ $ (from 0 to 25 $).

  - measure_id: bet_2
    text: |
      Experimenter: Okay, great! And again.
      And again, experimenter started recording signals and Subject wrote his bet. {{participant}} writes ___ cents (from 0 to 25 cents).
    variations:
    - variation_id: bets_in_dollars
      text: |
        Experimenter: Okay, great! And again.
        And again, experimenter started recording signals and Subject wrote his bet. {{participant}} writes ___ $ (from 0 to 25 $).

  - measure_id: bet_3
    text: |
      Experimenter: Okay, thank you! One more time.
      Experimenter started recording signals and Subject wrote his bet. {{participant}} writes ___ cents (from 0 to 25 cents).
    variations:
    - variation_id: bets_in_dollars
      text: |
        Experimenter: Okay, thank you! One more time.
        Experimenter started recording signals and Subject wrote his bet. {{participant}} writes ___ $ (from 0 to 25 $).

  - measure_id: bet_4
    text: |
      Experimenter: Okay! And finally.
      Experimenter started recording signals and Subject wrote his bet. {{participant}} writes ___ cents (from 0 to 25 cents).
    variations:
    - variation_id: bets_in_dollars
      text: |
        Experimenter: Okay! And finally.
        Experimenter started recording signals and Subject wrote his bet. {{participant}} writes ___ $ (from 0 to 25 $).
  
  - measure_id: confidence
    text: |
      Next, the experimenter asked one of the participants to leave the room, and the Subject decided to leave. After that, the experimenter conducted the remaining experiments and moved on to the questionnaire based on the results of the study. The questionnaire asked, "How competent would you rate the Subject on a scale from 1 to 6?". {{participant}} replied ___ (from 1 to 6).


# EXPERIMENT 2: EFFECTS OF CHOICE ON THE ILLUSION OF CONTROL
- experiment_id: choice

# EXPERIMENT 3: THE EFFECTS OF STIMULUS FAMILIARITY ON THE ILLUSION OF CONTROL AND A REPLICATION OF THE EFFECTS OF CHOICE
- experiment_id: stimulus_familiarity_choice
